site_name: TopHat drafts
site_description: Materials for Eco 100 course.
site_author: Hunter College Economics team
repo_name: TopHat Drafts for 100
repo_url: https://hunterecon2.github.io/tophat100/

nav:
    - Top Stuff:
      - Home: index.md
      - About: About.md
    - Content:
       - Geogebra: units/geogebra_examples.md
       - Power: units/Market-Power.md


# to install theme `pip install mkdocs-material`
theme:
    name: material  


# other settings ...

markdown_extensions:
   - admonition
   - pymdownx.arithmatex
  
plugins:
 - search
 #- mkpdfs


extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML


